/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2016 by:
 - Department of Geography, University of Bonn -
 and
 - lat/lon GmbH -

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
 ----------------------------------------------------------------------------*/
package org.deegree.sqldialect.table;

import org.deegree.commons.jdbc.SQLIdentifier;
import org.deegree.commons.jdbc.TableName;
import org.deegree.commons.tom.primitive.BaseType;

/**
 * Definition of a geometry column of a table in an SQL database.
 *
 * @author <a href="mailto:schneider@occamlabs.de">Markus Schneider</a>
 *
 * @since 3.4
 */
public class PrimitiveColumnDefinition extends ColumnDefinition {

    private final BaseType type;

    private boolean isPrimaryKey;

    private boolean isAutogenerated;

    private TableName pkTable;

    private boolean isCascadeOnDelete;

    /**
     * Creates a new <code>PrimitiveColumnDefinition</code> instance.
     * 
     * @param name
     *            name of the column, must not be <code>null</code>
     * @param type
     *            type of the column, must not be <code>null</code>
     */
    public PrimitiveColumnDefinition( final SQLIdentifier name, final BaseType type ) {
        super( name );
        this.type = type;
    }

    public PrimitiveColumnDefinition setIsNotNull() {
        isNotNull = true;
        return this;
    }

    public PrimitiveColumnDefinition setIsPrimaryKey() {
        isPrimaryKey = true;
        return this;
    }

    public PrimitiveColumnDefinition setIsAutogenerated() {
        isAutogenerated = true;
        return this;
    }

    public PrimitiveColumnDefinition setForeignKey( final TableName pkTable, final boolean isCascadeOnDelete ) {
        this.pkTable = pkTable;
        this.isCascadeOnDelete = isCascadeOnDelete;
        return this;
    }

    /**
     * Returns the type of the column.
     *
     * @return type of the column, never <code>null</code>
     */
    public BaseType getType() {
        return type;
    }

    /**
     * Returns whether the column is (part of) the primary key.
     *
     * @return <code>true</code>, if columns is (part of) the primary key, <code>false</code> otherwise
     */
    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }

    /**
     * Returns whether the value is automatically generated by the DB on insert.
     *
     * @return <code>true</code>, if database generates the value automatically on insert, <code>false</code> otherwise
     */
    public boolean isAutogenerated() {
        return isAutogenerated;
    }

    /**
     * Returns the referenced table (if the column is a foreign key column).
     *
     * @return referenced table, can be <code>null</code> (not a foreign key column)
     */
    public TableName getReferencedTable() {
        return pkTable;
    }

    /**
     * Returns whether this foreign key column cascades deletes.
     *
     * @return <code>true</code>, if this is a foreign key column that cascades deletes, <code>false</code> otherwise
     */
    public boolean getIsCascadeOnDelete() {
        return isCascadeOnDelete;
    }

    @Override
    public void merge( final ColumnDefinition other ) {
        if ( !( other instanceof PrimitiveColumnDefinition ) ) {
            throw new IllegalArgumentException();
        }
        final PrimitiveColumnDefinition that = (PrimitiveColumnDefinition) other;
        if ( that.pkTable != null ) {
            if ( this.pkTable != null ) {
                if ( !this.pkTable.equals( that.pkTable ) ) {
                    throw new IllegalArgumentException();
                }
            } else {
                this.pkTable = that.pkTable;
            }
        }
        this.isPrimaryKey = this.isPrimaryKey || that.isPrimaryKey;
        this.isNotNull = this.isNotNull || that.isNotNull;
        this.isAutogenerated = this.isAutogenerated || that.isAutogenerated;
        this.isCascadeOnDelete = this.isCascadeOnDelete || that.isCascadeOnDelete;
    }

}
